"""NL2SQL agent state definition.

In LangGraph, 'State' serves as the shared data contract (single source of truth)
that is passed from node to node throughout the graph execution.
Nodes receive the current state, perform operations, and return a dictionary
of state updates. LangGraph merges these updates into the state.
"""

from typing import Annotated, Any, Literal

from langgraph.graph.message import BaseMessage, add_messages
from pydantic import BaseModel


class Session(BaseModel):
    """Session metadata for tracking user conversations across multiple turns."""

    session_id: str
    metadata: dict[str, Any]


class State(BaseModel):
    """Complete state container for the NL2SQL agent workflow.
    
    This model defines all variables tracked and updated across the entire
    lifecycle of a query or conversation.
    """

    # --------------------------------------------------------------------------
    # Message History (with LangGraph Reducer)
    # --------------------------------------------------------------------------
    # The `Annotated[..., add_messages]` reducer is crucial:
    # Instead of replacing the entire message list when a node returns {"messages": [new_msg]},
    # LangGraph uses `add_messages` to append new messages to the existing list and
    # match existing messages by ID (e.g. for message updates/edits).
    messages: Annotated[list[BaseMessage], add_messages]

    # --------------------------------------------------------------------------
    # Intent & User Query
    # --------------------------------------------------------------------------
    # The raw text of the user's latest query or request.
    user_query: str | None = None

    # Classified intent:
    # - "sql":  User wants to query the database (triggers SQL generation pipeline)
    # - "chat": User wants general assistance, schema inquiry, or query explanation
    user_intent: Literal["sql", "chat"] | None = None

    # --------------------------------------------------------------------------
    # SQL Generation & Security Validation
    # --------------------------------------------------------------------------
    # The SQL query string generated by the LLM.
    sql_query: str | None = None

    # Step-by-step plain English explanation of the generated SQL query.
    sql_explanation: str | None = None

    # Safety status checked by `sql_safety_validator`:
    # - "safe":   Contains only read-only statements (e.g. SELECT)
    # - "unsafe": Contains destructive commands (DROP, DELETE, UPDATE, TRUNCATE, etc.)
    sql_safety_status: Literal["safe", "unsafe"] | None = None

    # --------------------------------------------------------------------------
    # SQL Syntax Validation & Self-Healing
    # --------------------------------------------------------------------------
    # Syntax validation status from PostgreSQL PREPARE statement test:
    # - "valid":   Query parsed and validated successfully by PostgreSQL
    # - "invalid": Query contains syntax or schema errors that could not be repaired
    sql_syntax_status: Literal["valid", "invalid"] | None = None

    # --------------------------------------------------------------------------
    # Human-in-the-Loop (HITL) Feedback
    # --------------------------------------------------------------------------
    # User's decision when asked for execution confirmation:
    # - "approved": User confirmed with 'yes' / 'y'
    # - "rejected": User declined with 'no'
    user_feedback_status: Literal["approved", "rejected"] | None = None

    # --------------------------------------------------------------------------
    # Database Execution & Result Analysis
    # --------------------------------------------------------------------------
    # Raw execution result from PostgreSQL (dictionary containing data records, row count, errors)
    sql_execution_result: dict[str, Any] | None = None

    # Execution status:
    # - "success": Query ran and returned data or affected rows without errors
    # - "failure": Database returned an execution error
    sql_execution_status: Literal["success", "failure"] | None = None

    # Natural language summary and data insights generated by the LLM from the result rows
    sql_execution_analysis: str | None = None

